services:
  nginx:
    container_name: 'nginx'
    build: nginx
    ports:
      - 80:80
      - 443:443
    command: nginx '-g' 'daemon off;'
  mariadb:
    container_name: 'mariadb'
    build: mariadb
    ports:
      - 3306:3306