services:

  mariadb:
    container_name: 'mariadb'
    build: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - connect_all

  wordpress:
    container_name: 'wordpress'
    build: wordpress
    ports:
      - 9000:9000
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_NAME=$ENV_WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER=$ENV_WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$ENV_WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_HOST=$ENV_WORDPRESS_DB_HOST
      - WORDPRESS_TABLE_PREFIX=$ENV_WORDPRESS_TABLE_PREFIX
      - WORDPRESS_DEBUG=$ENV_WORDPRESS_DEBUG
    networks:
      - connect_all

  nginx:
    container_name: 'nginx'
    build: nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - connect_all  

networks:
  connect_all:
    driver: bridge
