services:

  mariadb:
    container_name: 'mariadb'
    build: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    command: mysqld

  nginx:
    container_name: 'nginx'
    build: nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    command: nginx '-g' 'daemon off;'
  
  wordpress:
    container_name: 'wordpress'
    build: wordpress
    ports:
      - 9000:9000
    restart: unless-stopped
    depends_on:
      - mariadb

