CREATE USER IF NOT EXISTS 'Tess'@'localhost' IDENTIFIED BY 'DB_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress_db.* TO 'Tess'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER IF NOT EXISTS 'basic'@'localhost' IDENTIFIED BY 'DB_USER_PASSWORD';
GRANT USAGE ON wordpress_db.* TO 'basic'@localhost;
FLUSH PRIVILEGES;
EXIT